field.storage.*.*.third_party.field_encrypt:
  type: mapping
  label: 'Field encrypt setting'
  mapping:
    encrypt:
      type: boolean
      label: 'Encrypt'
    properties:
      type: sequence
      label: 'Properties'
      sequence:
        type: string
        label: 'Property'
    placeholders:
      type: sequence
      label: 'Properties placeholders'
      sequence:
        type: string
        label: 'Placeholder'

field_encrypt.settings:
  type: config_object
  label: 'Field Encrypt Settings'
  mapping:
    encryption_profile:
      type: string
      label: 'Encryption profile'
    make_entities_uncacheable:
      type: boolean
      label: 'Exclude from persistent caches'
    default_properties:
      type: sequence
      label: 'Field types'
      sequence:
        type: sequence
        label: 'Properties to encrypt'
        sequence:
          type: string
          label: 'Property name'
    batch_size:
      type: integer
      label: 'Batch size'

field_encrypt.entity_type.*:
  type: config_entity
  mapping:
    id:
      type: string
      label: 'Entity type ID'
    base_fields:
      type: sequence
      label: 'Encrypted base fields'
      sequence:
        type: sequence
        label: 'Base field'
        sequence:
          type: string
          label: 'Base field property'
