name: iamhere
type: Site
description: Custom recipe for the I Am Here site.
install:
- address
- ai
- default_content
- entity
- flag
- key
- privatemsg
- profile
- select_or_other
- smtp
- telephone
- terms_of_use
- views_bulk_operations
- webform
config:
  strict:
  - field.storage.node.field_contact_name
  - field.storage.node.field_email
  - field.storage.node.field_organization_address
  - field.storage.node.field_phone
  - field.storage.node.field_restaurant_address
  - field.storage.node.field_restaurant_description
  - field.storage.node.field_restaurant_name
  - field.storage.node.field_restaurant_price
  - field.storage.node.field_restaurant_space
  - field.storage.profile.field_address
  - field.storage.profile.field_dob
  - field.storage.profile.field_first
  - field.storage.profile.field_gender
  - field.storage.profile.field_last
  - field.storage.profile.field_photo
  - field.storage.profile.field_politics
  - field.storage.profile.field_race
  - field.storage.profile.field_religion
  import:
    ai:
    - ai.settings
    field:
    - field.field.node.organization.field_organization_address
    - field.field.node.restaurant.field_contact_name
    - field.field.node.restaurant.field_email
    - field.field.node.restaurant.field_phone
    - field.field.node.restaurant.field_restaurant_address
    - field.field.node.restaurant.field_restaurant_description
    - field.field.node.restaurant.field_restaurant_name
    - field.field.node.restaurant.field_restaurant_price
    - field.field.node.restaurant.field_restaurant_space
    - field.field.profile.demographics.field_address
    - field.field.profile.demographics.field_dob
    - field.field.profile.demographics.field_gender
    - field.field.profile.demographics.field_politics
    - field.field.profile.demographics.field_race
    - field.field.profile.demographics.field_religion
    - field.field.profile.friend.field_first
    - field.field.profile.friend.field_last
    - field.field.profile.friend.field_photo
    node:
    - node.type.community
    - node.type.organization
    - node.type.restaurant
    - core.entity_form_display.node.community.default
    - core.entity_form_display.node.organization.default
    - core.entity_form_display.node.restaurant.default
    - core.entity_view_display.node.organization.default
    - core.entity_view_display.node.restaurant.default
    profile:
    - profile.type.ambassador
    - profile.type.demographics
    - profile.type.friend
    - profile.type.organizer
    - core.entity_form_display.profile.demographics.default
    - core.entity_form_display.profile.friend.default
    - core.entity_view_display.profile.demographics.default
    - core.entity_view_display.profile.friend.default
    system:
    - system.action.flag_delete_flagging
    - system.action.profile_delete_action
    - system.action.profile_publish_action
    - system.action.profile_unpublish_action
    - system.action.user_add_role_action.ambassador
    - system.action.user_add_role_action.friend
    - system.action.user_add_role_action.organizer
    - system.action.user_remove_role_action.ambassador
    - system.action.user_remove_role_action.friend
    - system.action.user_remove_role_action.organizer
    user:
    - user.role.ambassador
    - user.role.friend
    - user.role.organizer
    - core.entity_form_display.user.user.register
  actions:
    ai.settings:
      simpleConfigUpdate:
        prompt_logging: false
        prompt_logging_tags: ''
        default_providers: {}
